name: decksly
description: Hearthstone card collector.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  freezed: ^2.3.2
  equatable: ^2.0.3
  rxdart: ^0.27.4

  # DI
  get_it: ^7.2.0
  injectable: ^1.5.3

  # Navigation
  go_router: ^3.0.4

  # Testing
  #mocktail: ^0.3.0

  # Code Generation
  build_runner: ^2.1.8

  # Networking
  dio: ^4.0.0
  retrofit: ^3.0.1+1
  json_annotation: ^4.6.0
  flutter_secure_storage: ^7.0.0
  connectivity_plus: ^2.3.4

  # Firebase
  firebase_storage: ^10.2.7
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.0

  # UI
  flutter_screenutil: ^5.6.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^1.2.1
  infinite_scroll_pagination: ^3.2.0
  foil: ^0.9.0+1
  flutter_svg: ^0.23.0+1
  auto_size_text: ^3.0.0-nullsafety.0

  # Util
  flutter_markdown: ^0.6.13
  flutter_html: ^2.2.1

  # Dev
  logger: ^1.1.0
  xl: ^0.9.1
  flip_card: ^0.6.0

dev_dependencies:
  lint: ^1.5.3
  json_serializable: ^6.3.1
  injectable_generator: ^1.5.3
  retrofit_generator: ^4.1.1

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    # Backgrounds
    - assets/background/scroll_background.png
    - assets/background/velvet_background_top.png
    - assets/background/velvet_background_center.jpg
    - assets/background/velvet_background_bottom.png

    # Shared
    - assets/shared/border_left_outline.png
    - assets/shared/border_center_outline.png
    - assets/shared/border_right_outline.png

    # Button
    - assets/button/button_border_left.png
    - assets/button/button_border_center.png
    - assets/button/button_border_right.png

    # Search
    - assets/search/search_border_left.png
    - assets/search/search_border_center.png
    - assets/search/search_border_right.png

    # Dropdown
    - assets/dropdown/dropdown_background.png
    - assets/dropdown/dropdown_button_border_left.png
    - assets/dropdown/dropdown_border_bottom.png
    - assets/dropdown/dropdown_border_bottom_left.png
    - assets/dropdown/dropdown_border_bottom_right.png
    - assets/dropdown/dropdown_border_left.png
    - assets/dropdown/dropdown_border_right.png
    - assets/dropdown/dropdown_border_top.png
    - assets/dropdown/dropdown_border_top_left.png
    - assets/dropdown/dropdown_border_top_right.png

    # Sets
    - assets/set/standard.svg
    - assets/set/wild.svg
    - assets/set/classic.svg
    - assets/set/currentArenaCards.svg
    - assets/set/currentDuelsCards.svg
    - assets/set/pathOfArthas.svg
    - assets/set/marchOfTheLichKing.svg
    - assets/set/murderAtCastleNathria.svg
    - assets/set/voyageToTheSunkenCity.svg
    - assets/set/fracturedInAlteracValley.svg
    - assets/set/unitedInStormwind.svg
    - assets/set/forgedInTheBarrens.svg
    - assets/set/core.svg
    - assets/set/madnessAtTheDarkmoonFaire.svg
    - assets/set/scholomanceAcademy.svg
    - assets/set/demonHunterInitiate.svg
    - assets/set/ashesOfOutland.svg
    - assets/set/galakrondsAwakening.svg
    - assets/set/descentOfDragons.svg
    - assets/set/saviorsOfUldum.svg
    - assets/set/riseOfShadows.svg
    - assets/set/rastakhansRumble.svg
    - assets/set/theBoomsdayProject.svg
    - assets/set/theWitchwood.svg
    - assets/set/koboltsAndCatacombs.svg
    - assets/set/knightsOfTheFrozenThrone.svg
    - assets/set/journeyToUnGoro.svg
    - assets/set/meanStreetsOfGadgetzan.svg
    - assets/set/oneNightInKarazhan.svg
    - assets/set/whispersOfTheOldGods.svg
    - assets/set/leagueOfExplorers.svg
    - assets/set/theGrandTournament.svg
    - assets/set/blackrockMountain.svg
    - assets/set/goblinsVsGnomes.svg
    - assets/set/curseOfNaxxramas.svg
    - assets/set/legacy.svg

    # Class
    - assets/class/all_icon.png
    - assets/class/neutral_icon.png
    - assets/class/deathKnight_icon.png
    - assets/class/demonHunter_icon.png
    - assets/class/druid_icon.png
    - assets/class/hunter_icon.png
    - assets/class/mage_icon.png
    - assets/class/paladin_icon.png
    - assets/class/priest_icon.png
    - assets/class/rogue_icon.png
    - assets/class/shaman_icon.png
    - assets/class/warlock_icon.png
    - assets/class/warrior_icon.png

    # Misc
    - assets/misc/mana.png
    - assets/misc/mana_active.png
    - assets/misc/mana_inactive.png
    - assets/misc/golden_circle_border.png
    - assets/misc/filter.svg

  fonts:
    - family: Belwe
      fonts:
        - asset: assets/fonts/Belwe-Medium.ttf
        - asset: assets/fonts/Belwe-Light.ttf
          weight: 300
        - asset: assets/fonts/Belwe-Bold.ttf
          weight: 700
